#!/bin/bash
. /usr/share/libubox/jshn.sh

TIMEOUT=60
IP='192.168.9.163'
PORT=3001
DEPARTMENT_ID='60daba810749b827e0cb8448'
response=$(curl --location --request GET "http://$IP:$PORT/api/devices/?id=$DEPARTMENT_ID")
echo $response

while true
do

	if [ -f /etc/firewall.user ]; then
			rm /etc/firewall.user
	fi

	count=$(grep -o -i "mac" $response | wc -l)

	i=0; while [ $i -lt $count ]; do

			test=$(cat $response | jq '(."$i") | {mac, allowed}')

			json_load "$test"

			json_select

			json_get_var mac mac

			json_get_var allowed allowed

			echo "Device with mac: $mac - allowed: $allowed"

			if [ $allowed -eq 1 ]; then

					echo "iptables -A INPUT -m mac --mac-source $mac -j DROP" >> /etc/firewall.user

					echo "iptables -A FORWARD -m mac --mac-source $mac -j DROP" >> /etc/firewall.user
			fi

			i=$(($i + 1))

	done

    sleep $TIMEOUT
done
